FROM alpine:latest
# This is a dummy secret for demonstration purposes.
# In a real scenario, this could be an API key, password, or private key.
ENV API_KEY="dummy_api_key_for_demonstration_only_12345"
COPY secret.txt /
CMD ["sleep", "3600"]
